### ISSUE TITLE
works in Scratch, not on Leopard 

### ISSUE THREAD

**Issue by Rochee88** [PullJosh/leopard-website#11]
Hey Josh
so excited to get my game onto Vercel.
My game works OK on the Scratch site but crashes on https://leopardjs.now.sh/
Any hints ??
Here 'tis
https://scratch.mit.edu/projects/490285759/
Where to from here?
cheers
Rob

**Comment by PullJosh** [comment]
Hi Rob!

First of all, I love your game!

When I ran your project with Leopard, it seemed to load up okay. I was able to start a new game. But I couldn't move my pieces! I am guessing that Leopard behaves slightly differently than Scratch when it comes to the "stop this script" block. I'm not sure exactly what the difference is, but that seems like an area that might be problematic.

Maybe try editing your project to avoid using that block? There's no guarantee it will work, but it's the best idea I have.

**Comment by Rochee88** [comment]
Thanks heaps!
I’ll start there :)
