### ISSUE TITLE
"There was an error compiling this project" message displays black on black

### ISSUE THREAD

**Issue by towerofnix** [PullJosh/leopard-website#2]
Here I've highlighted that error message, so you can see it:

![highlighted error message (white text, blue background) on a black background in the stage area](https://user-images.githubusercontent.com/9948030/72681563-2b5bcd80-3a9b-11ea-818b-f5ab10611991.png)

If you don't highlight it (e.g. because you think the project is still loading), you'll only see a black stage area!

**Comment by MTM828** [comment]
Same with https://scratch.mit.edu/projects/445582283/. I think mine isn't working because it's too big, how big was your's? Perhaps Leapord can't handle huge projects.

**Comment by PullJosh** [comment]
Fixed in the website redesign
