### ISSUE TITLE
Implement a "download as zip" button/mode

### ISSUE THREAD

**Issue by towerofnix** [PullJosh/leopard-website#33]
It would be nice to have a way to generate a standalone zip of a project converted to Leopard. Preferably, this package would work without internet access; I've [already implemented](https://github.com/leopard-js/sb-edit/pull/91) an option to include reference Leopard library files packaged locally rather than online.

We might want to show a brief modal describing how to work on the project locally (like opening source files in a text editor and using the terminal to cd to the project directory and run a simple HTTP server), especially if we implement TypeScript integration (basic familiarization with `npm install` and `npm start` commands, maybe an `npm build` command for standalone all-in-one "My Project.html" type export).

**Comment by PullJosh** [comment]
We could add some additional niceties around this (like the instructions modal or making it run in-browser), but the basic functionality is now there.

**Comment by towerofnix** [comment]
This refers to the dropdown menu before you convert, right?

<img width="288" alt="Edit as JavaScript button on homepage, with the bottom option in a dropdown, Download .zip, highlighted" src="https://github.com/PullJosh/leopard-website/assets/9948030/c681b6a8-7cdd-4245-954d-99a96330dd6a">

No "File" menu in the editor, so no way to save a backup of your ongoing work... but that's a separate issue really. Nice, nice.

**Comment by PullJosh** [comment]
True. I suppose uploading a ZIP would also be a useful feature.
