### ISSUE TITLE
Some strangeness in tab view flex layout

### ISSUE THREAD

**Issue by towerofnix** [PullJosh/leopard-website#42]
Here's the layout for the editor tabs, running Safari 17.4.1:

<img width="652" src="https://github.com/PullJosh/leopard-website/assets/9948030/9a113eb0-3dcb-4378-857a-da33804c405c">

Pink lines are the main `flex-direction: row` container, blue/cyan lines are the "Create" button - which really is that wide.

Possibly flex-shrink or flex-basis is needed on the create button? Here's the same view if we add `flex-basis: 200px`:

<img width="639" src="https://github.com/PullJosh/leopard-website/assets/9948030/bd5f9dd4-293a-467d-9edf-18ec070315ae">

**Comment by PullJosh** [comment]
Good catch! Thank you
