### ISSUE TITLE
Profile dropdown has horizontal overflow issue

### ISSUE THREAD

**Issue by towerofnix** [PullJosh/leopard-website#43]
Looks like something's not lining up here:

<img width="224" alt="Profile dropdown with a horizontal scrollbar, though it only has a tiny bit of space past the right edge" src="https://github.com/PullJosh/leopard-website/assets/9948030/cc9c1b5e-8dd4-4216-aae5-14a7934713c5">

Safari 17.4.1. The scrollable overflow is present regardless of window dimensions and regardless whether scrollbars are set to show always (above) or only when scrolling.

**Comment by PullJosh** [comment]
Thanks!
