### ISSUE TITLE
Birthday month input broken in some browsers

### ISSUE THREAD

**Issue by PullJosh** [PullJosh/leopard-website#51]
https://scratch.mit.edu/discuss/topic/420162/?page=53#post-8037209

> Potential bug? I can't register an account in brave browser, as the birthday month field resets everytime I click away from it. I can set a date just fine, but clicking anywhere (including the register button) clears it again. Also, the current format is “January 2000”, while below the box it says that the format should be “YYYY-MM”.
> 
> Using Firefox, the Format is correct, where it's YYYY-MM, but typing in 1998-04 for example, always deletes the “0” after clicking away, which makes me unable to register.

https://scratch.mit.edu/projects/1043871984/#comments-412442313

> "if I register with my month "02" it automatically goes to "2" and doesn't accept it" [...] I'm using Firefox in macOS

**Comment by towerofnix** [comment]
I can reproduce this:

* on Firefox 115 (esr) on macOS
* on Safari 17.5 on macOS

But not on Chrome 126 on macOS, where the prompt is completely different:

<img width="272" alt="February 2024 in Birthday Month input, with February selection-highlighted" src="https://github.com/PullJosh/leopard-website/assets/9948030/af152fb7-e13d-476c-83c5-a07877769f45">

It clears as soon as I tab out of the input (or move focus in general, e.g. click Register):

<img width="349" alt="Empty input showing a bunch of dashes, a space, and then four more dashes" src="https://github.com/PullJosh/leopard-website/assets/9948030/a3ae6cee-d960-4be7-a814-ad3a4d193918">

**Comment by towerofnix** [comment]
Note Brave and many other browsers are based on Chromium, and would have the same strange prompt shown above.

**Comment by PullJosh** [comment]
Since `<input type="month" />` support seems to be all over the place, I think it makes sense to replace this with a pair of dropdowns. One for the month and one for the year. Keep it simple.

**Comment by PullJosh** [comment]
Should be fixed by 03a0e87
